[package]
name = "source_files"
version = "0.1.0"
edition = "2024"

[dependencies]
append_only_vec = { version = "0.1.0", path = "../../support/append_only_vec" }
line_column = { version = "0.1.0", path = "../../support/line_column" }
