[package]
name = "text"
version = "0.1.0"
edition = "2024"

[dependencies]
infinite_iterator = { version = "0.1.0", path = "../infinite_iterator" }
line_column = { version = "0.1.0", path = "../line_column" }
source_files = { version = "0.1.0", path = "../../representations/source_files" }
