[package]
name = "asg"
version = "0.1.0"
edition = "2024"

[dependencies]
ast = { version = "0.1.0", path = "../ast" }
ast_workspace = { version = "0.1.0", path = "../ast_workspace" }
attributes = { version = "0.1.0", path = "../attributes" }
derive_more.workspace = true
diagnostics = { version = "0.1.0", path = "../../support/diagnostics" }
fs_tree = { version = "0.1.0", path = "../fs_tree" }
indexmap.workspace = true
interpreter_api = { version = "0.1.0", path = "../interpreter_api" }
itertools.workspace = true
num.workspace = true
ordered-float.workspace = true
primitives = { version = "0.1.0", path = "../primitives" }
slotmap.workspace = true
source_files = { version = "0.1.0", path = "../source_files" }
target = { version = "0.1.0", path = "../../support/target" }
