[package]
name = "ast"
version = "0.1.0"
edition = "2024"

[dependencies]
append_only_vec = { version = "0.1.0", path = "../../support/append_only_vec" }
arena = { version = "0.1.0", path = "../../support/arena" }
ast_workspace_settings = { version = "0.1.0", path = "../ast_workspace_settings" }
attributes = { version = "0.1.0", path = "../attributes" }
derive_more.workspace = true
fs_tree = { version = "0.1.0", path = "../fs_tree" }
indexmap.workspace = true
interpreter_api = { version = "0.1.0", path = "../interpreter_api" }
num.workspace = true
num-bigint.workspace = true
primitives = { version = "0.1.0", path = "../primitives" }
smallvec = "1.15.0"
source_files = { version = "0.1.0", path = "../source_files" }
std_ext = { version = "0.1.0", path = "../../support/std_ext" }
token = { version = "0.1.0", path = "../token" }
