[package]
name = "pp_token"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
inflow = { version = "0.1.0", path = "../../support/inflow" }
source_files = { version = "0.1.0", path = "../source_files" }
