[package]
name = "interpreter_api"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
num-bigint.workspace = true
primitives = { version = "0.1.0", path = "../primitives" }
