[package]
name = "target_layout"
version = "0.1.0"
edition = "2024"

[dependencies]
arena = { version = "0.1.0", path = "../arena" }
asg = { version = "0.1.0", path = "../../representations/asg" }
data_units = { version = "0.1.0", path = "../data_units" }
derivative.workspace = true
diagnostics = { version = "0.1.0", path = "../diagnostics" }
ir = { version = "0.1.0", path = "../../representations/ir" }
once_map.workspace = true
primitives = { version = "0.1.0", path = "../../representations/primitives" }
source_files = { version = "0.1.0", path = "../../representations/source_files" }
target = { version = "0.1.0", path = "../target" }
