[package]
name = "c_token"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
inflow = { version = "0.1.0", path = "../../support/inflow" }
num-bigint.workspace = true
pp_token = { version = "0.1.0", path = "../pp_token" }
source_files = { version = "0.1.0", path = "../source_files" }
