[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
diagnostics = { version = "0.1.0", path = "../diagnostics" }
source_files = { version = "0.1.0", path = "../../representations/source_files" }
